### ISSUE TITLE
Has the API changed again?

### ISSUE THREAD

**Issue by peteralm097** [imcfarla2003/domoticz-hive#25]
2022-04-13 17:32:17.097 Error: Hive: Call to function 'onHeartbeat' failed, exception details:
2022-04-13 17:32:17.099 Error: Hive: Traceback (most recent call last):
2022-04-13 17:32:17.099 Error: Hive: File "/home/pi/domoticz/plugins/domoticz-hive/plugin.py", line 916, in onHeartbeat
2022-04-13 17:32:17.099 Error: Hive: _plugin.onHeartbeat()
2022-04-13 17:32:17.099 Error: Hive: File "/home/pi/domoticz/plugins/domoticz-hive/plugin.py", line 194, in onHeartbeat
2022-04-13 17:32:17.100 Error: Hive: d = self.GetDevices()
2022-04-13 17:32:17.100 Error: Hive: File "/home/pi/domoticz/plugins/domoticz-hive/plugin.py", line 869, in GetDevices
2022-04-13 17:32:17.100 Error: Hive: req = Request(url, headers = headers, unverifiable = True)
2022-04-13 17:32:17.100 Error: Hive: File "/usr/lib/python3.7/urllib/request.py", line 328, in __init__
2022-04-13 17:32:17.100 Error: Hive: self.full_url = url
2022-04-13 17:32:17.100 Error: Hive: File "/usr/lib/python3.7/urllib/request.py", line 354, in full_url
2022-04-13 17:32:17.100 Error: Hive: self._parse()
2022-04-13 17:32:17.100 Error: Hive: File "/usr/lib/python3.7/urllib/request.py", line 383, in _parse
2022-04-13 17:32:17.100 Error: Hive: raise ValueError("unknown url type: %r" % self.full_url)
2022-04-13 17:32:17.100 Error: Hive: ValueError: unknown url type: '/omnia/nodes'

**Comment by Mark-Sellwood** [comment]
I think the answer is yes, Google Home cant connect anymore.

**Comment by imcfarla2003** [comment]
Not had any problem myself...

Is it still an issue?

**Comment by damo9999** [comment]
I am getting the same error messages and the plug-in isn’t updating my Hive heating devices. My issue started later though, I can see in my devices logs there are updated values until about 1am on the 17th.

I am also getting status messages about acquiring/releasing lock multiple times a second (I think I was getting these even when it worked though).

2022-04-21 16:45:44.696 (Hive) Acquiring lock for 'Hive'
2022-04-21 16:45:44.696 (Hive) Releasing lock for 'Hive'
2022-04-21 16:45:44.746 (Hive) Acquiring lock for 'Hive'
2022-04-21 16:45:44.746 (Hive) Releasing lock for 'Hive'

**Comment by peteralm097** [comment]
Sadly, still an issue...

2022-05-29 11:48:23.425 Hive: Pushing 'onMessageCallback' on to queue
2022-05-29 11:48:23.425 Hive: Acquiring GIL for 'ReadEvent'
2022-05-29 11:48:23.425 Hive: Processing 'onMessageCallback' message
2022-05-29 11:48:23.425 Hive: Acquiring GIL for 'onMessageCallback'
2022-05-29 11:48:23.425 Hive: Calling message handler 'onMessage' on 'module' type object.
2022-05-29 11:48:23.425 Hive: onMessage called for Hive Session
2022-05-29 11:48:23.425 Hive: Error Creating Session
2022-05-29 11:48:23.425 Hive: 403
2022-05-29 11:48:23.425 Hive: Pushing 'DisconnectDirective' on to queue
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'onMessageCallback'
2022-05-29 11:48:23.426 Hive: Processing 'DisconnectDirective' message
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectDirective'
2022-05-29 11:48:23.426 Hive: Disconnect directive received for 'beekeeper.hivehome.com:443'.
2022-05-29 11:48:23.426 Hive: Handling TCP disconnect, socket (beekeeper.hivehome.com:443) is connected
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'CPluginTransportTCP::handleRead'
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectDirective'
2022-05-29 11:48:23.426 Hive: Queued asynchronous secure read aborted.
2022-05-29 11:48:23.426 Hive: Pushing 'DisconnectedEvent' on to queue
2022-05-29 11:48:23.426 Hive: Processing 'DisconnectedEvent' message
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectedEvent'
2022-05-29 11:48:23.426 Hive: Disconnect event received for 'beekeeper.hivehome.com:443'.
2022-05-29 11:48:23.427 Hive: Pushing 'onDisconnectCallback' on to queue
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'DisconnectedEvent'
2022-05-29 11:48:23.427 Hive: Processing 'onDisconnectCallback' message
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'onDisconnectCallback'
2022-05-29 11:48:23.427 Hive: Calling message handler 'onDisconnect' on 'module' type object.
2022-05-29 11:48:23.427 Hive: onDisconnect called for Hive Session
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'onDisconnectCallback'
2022-05-29 11:48:23.305 Error: Hive: Error getting weather information
2022-05-29 11:48:23.305 Error: Hive: CConnection_disconnect, disconnection request from 'Hive' ignored. Transport does not exist.

**Comment by imcfarla2003** [comment]
I think it is the the end of this plugin.The API has been vastly changed and after 4 hours I can login but that is about it.On 29 May 2022 11:49, peteralm097 ***@***.***> wrote:
Sadly, still an issue...
2022-05-29 11:48:23.425 Hive: Pushing 'onMessageCallback' on to queue
2022-05-29 11:48:23.425 Hive: Acquiring GIL for 'ReadEvent'
2022-05-29 11:48:23.425 Hive: Processing 'onMessageCallback' message
2022-05-29 11:48:23.425 Hive: Acquiring GIL for 'onMessageCallback'
2022-05-29 11:48:23.425 Hive: Calling message handler 'onMessage' on 'module' type object.
2022-05-29 11:48:23.425 Hive: onMessage called for Hive Session
2022-05-29 11:48:23.425 Hive: Error Creating Session
2022-05-29 11:48:23.425 Hive: 403
2022-05-29 11:48:23.425 Hive: Pushing 'DisconnectDirective' on to queue
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'onMessageCallback'
2022-05-29 11:48:23.426 Hive: Processing 'DisconnectDirective' message
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectDirective'
2022-05-29 11:48:23.426 Hive: Disconnect directive received for 'beekeeper.hivehome.com:443'.
2022-05-29 11:48:23.426 Hive: Handling TCP disconnect, socket (beekeeper.hivehome.com:443) is connected
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'CPluginTransportTCP::handleRead'
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectDirective'
2022-05-29 11:48:23.426 Hive: Queued asynchronous secure read aborted.
2022-05-29 11:48:23.426 Hive: Pushing 'DisconnectedEvent' on to queue
2022-05-29 11:48:23.426 Hive: Processing 'DisconnectedEvent' message
2022-05-29 11:48:23.426 Hive: Acquiring GIL for 'DisconnectedEvent'
2022-05-29 11:48:23.426 Hive: Disconnect event received for 'beekeeper.hivehome.com:443'.
2022-05-29 11:48:23.427 Hive: Pushing 'onDisconnectCallback' on to queue
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'DisconnectedEvent'
2022-05-29 11:48:23.427 Hive: Processing 'onDisconnectCallback' message
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'onDisconnectCallback'
2022-05-29 11:48:23.427 Hive: Calling message handler 'onDisconnect' on 'module' type object.
2022-05-29 11:48:23.427 Hive: onDisconnect called for Hive Session
2022-05-29 11:48:23.427 Hive: Acquiring GIL for 'onDisconnectCallback'
2022-05-29 11:48:23.305 Error: Hive: Error getting weather information
2022-05-29 11:48:23.305 Error: Hive: CConnection_disconnect, disconnection request from 'Hive' ignored. Transport does not exist.

**Comment by Mark-Sellwood** [comment]
FYI Hive & Google are still not playing together.
Google connects to Hive but shows all devices as off line.

**Comment by Mark-Sellwood** [comment]
Latest update from Hive
The nano 1 hubs do not work with Google Home as they don't report device changes.
Hive want me to buy a new system at my expense.
The End of Hive for me.

**Comment by damo9999** [comment]
> I think it is the the end of this plugin. The API has been vastly changed and after 4 hours I can login but that is about it.>

That's a shame. Thanks for all your work on this over the years, it was good while it lasted.

The guys at Home Assistant seem to have got their integration working again so am migrating to that for now. 

I have been using this in conjunction with a Z wave switch to workaround deficiencies in my wiring/plumbing so will probably have to bite the bullet and get a plumber/heating company do a proper fix as probably only a matter of time until even the HA one breaks again. Problem is finding anyone to do this work is proving difficult.
